AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Initialize infrastructure

Parameters:
  EcrName:
    Type: String
    Description: ECR Name
    Default: text-to-preset

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep three untagged images, expire all others",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 3
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 2,
                "description": "Keep 30 tagged images , expire all others",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPatternList": ["*"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  ECR:
    Value: !Ref ECR
  RepositoryUri:
    Value: !GetAtt ECR.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-repository-uri"
