# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Initialize infrastructure

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  init-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::400827480311:role/Github-actions
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize infrastructure
        working-directory: ./cloudformation
        run: |
          aws cloudformation deploy --template-file shared-infra.yml --parameter-overrides EcrName=${{ github.event.repository.name }} --stack-name "${{github.event.repository.name}}-shared-infra" --capabilities CAPABILITY_NAMED_IAM --region ${{ env.AWS_REGION }}
